### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by W1ldish** [Tereneckla/wotlk#21]
Need to implement the set bonus for :
https://www.wowhead.com/wotlk/item=31338/charlottes-ivy
https://www.wowhead.com/wotlk/item=31339/lolas-eve

**Comment by Tereneckla** [comment]
Completed with https://github.com/Tereneckla/wotlk/commit/6fd404c73761ffd693b642ceadecd00698a5aa84
