### ISSUE TITLE
Missing items: [BRILLIANT WIZARD OIL] (for warlock)

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#24]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=20749/brilliant-wizard-oil

good oil for warlock even in TBC

**Comment by Tereneckla** [comment]
Warlock Stones added to regular consume picker
Warlocks have the regular consume picker now
