### ISSUE TITLE
Missing items: Totems, Librams & Idols

### ISSUE THREAD

**Issue by W1ldish** [Tereneckla/wotlk#25]
[Totem of Impact](https://www.wowhead.com/wotlk/item=27947/totem-of-impact "https://www.wowhead.com/wotlk/item=27947/totem-of-impact") and [Totem of Impact](https://www.wowhead.com/wotlk/item=27984/totem-of-impact "https://www.wowhead.com/wotlk/item=27984/totem-of-impact") (Horde & Alliance versions)
[Totem of Rage](https://www.wowhead.com/wotlk/item=22395/totem-of-rage "https://www.wowhead.com/wotlk/item=22395/totem-of-rage") (same function)

[Libram of Avengement](https://www.wowhead.com/wotlk/item=27484/libram-of-avengement "https://www.wowhead.com/wotlk/item=27484/libram-of-avengement")
[Libram of the Eternal Rest](https://www.wowhead.com/wotlk/item=27917/libram-of-the-eternal-rest "https://www.wowhead.com/wotlk/item=27917/libram-of-the-eternal-rest")
[Libram of Wracking](https://www.wowhead.com/wotlk/item=28065/libram-of-wracking "https://www.wowhead.com/wotlk/item=28065/libram-of-wracking")

[Idol of Savagery](https://www.wowhead.com/wotlk/item=27989/idol-of-savagery "https://www.wowhead.com/wotlk/item=27989/idol-of-savagery") and [Idol of Savagery](https://www.wowhead.com/wotlk/item=27990/idol-of-savagery "https://www.wowhead.com/wotlk/item=27990/idol-of-savagery") (Horde & Alliance versions)
[Idol of Terror](https://www.wowhead.com/wotlk/item=33509/idol-of-terror "https://www.wowhead.com/wotlk/item=33509/idol-of-terror")
[Idol of the Moon](https://www.wowhead.com/wotlk/item=23197/idol-of-the-moon "https://www.wowhead.com/wotlk/item=23197/idol-of-the-moon")

I couldn't verify [Idol of Ursoc](https://www.wowhead.com/wotlk/item=27744/idol-of-ursoc "https://www.wowhead.com/wotlk/item=27744/idol-of-ursoc").

**Comment by Tereneckla** [comment]
Pure bonus to spell x are handled in that spells file
Added the other missing ones
