### ISSUE TITLE
Rogue Combat Talent Preset

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#27]
Current Behavior:
At the moment the preset combat talents for rogue picks Close Quarters Combat (dagger specialization) instead of Hack and Slash (sword/axe specialization)

Expected Behavior:
Combat rogues generally use swords and axes so it would make sense for that talent to be the preset pick (i know you can change talents but people might miss it)

**Comment by Tereneckla** [comment]
Give me a good preset and I will set it to that
Either as one of the importable types or directly as the talent string found in the json export

**Comment by Icebeam666** [comment]
All other talents were right actually : )
here is talent string from the json export: 
"talentsString": "00532-0252051000035015223100501251",

**Comment by Tereneckla** [comment]
Thank you
