### ISSUE TITLE
Missing items: [Items from Beast Boss in Karazhan]

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#28]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:

Would it be possible to have the random suffix on these items as options?

https://www.wowhead.com/wotlk/item=30684/ravagers-cuffs
https://www.wowhead.com/wotlk/item=30685/ravagers-wrist-wraps
https://www.wowhead.com/wotlk/item=30687/ravagers-bracers
https://www.wowhead.com/wotlk/item=30686/ravagers-bands
https://www.wowhead.com/wotlk/item=30681/gliders-boots
https://www.wowhead.com/wotlk/item=30683/gliders-greaves
https://www.wowhead.com/wotlk/item=30682/gliders-sabatons
https://www.wowhead.com/wotlk/item=30680/gliders-foot-wraps
https://www.wowhead.com/wotlk/item=30678/lurkers-girdle
https://www.wowhead.com/wotlk/item=30676/lurkers-grasp
https://www.wowhead.com/wotlk/item=30677/lurkers-belt
https://www.wowhead.com/wotlk/item=30675/lurkers-cord

**Comment by Tereneckla** [comment]
Possible, yes
Unlikely, also yes

For now you can manually edit you stats for those items

**Comment by Tereneckla** [comment]
Actually just found a way to add those things
Now I just need to find the formula that calculates the items stats

**Comment by Tereneckla** [comment]
And they are mostly working in
You have to open and close the gear selector to update the suffix selector
