### ISSUE TITLE
Crash Report -138857697

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#29]
Link:
https://tereneckla.github.io/wotlk/rogue/#eJztU0toE0EY3n+y2W6WSMYlNGsuxsFDKRRmNyxUEWb0pHgpghB6qojiQbDmUFAPNiIoHvSahqrgKVQQwUtLqYi2lB7ESm1ECSapDcSDMcHGFIyPmV2PikTamx/Dz87/PYZ5rBHTEUVnYBSNA+QBpgGWAWoAh3ACDQKHFIzCdY8yxTx+P3gFtKGzJy6cSutBrMVfgxHBG2tgzcaINvENSrNgqHihKtsrZbCmRLuzCWIYYfxsDqwGIoGiEJm4JVzVKAkV6/Cl/ktx7QdYM2ESkDERXBMBV6NEE3ppCePJChDt5mdPbOIFQc/HRIBHFz1LpgRWRVhEgBSpeLUs64eSrItVWe9UwOjB6xtgNaMiZbIkP0jId9TrUrJeBmLoBo0M6Sl9RL2HniMji5T/+C1M2q3joqqDhYYTRi9W+9BggKPDwSwcz8OBh3B0GvriGhZ8wrwBhFI36QxQx3Woa1OX0qRLbeo4SVsw1HZcew10/WkV4TcvkHi3DTByoLwFJYcU8h6FvPWepPlOf+Uo35WbkFhi+/zOMttz2kOBOY9Q4ogV7N/mq25k+FbEjC/Nb0lON/DPbO4TP+jPN9kIHPN+jrGsPNUma8Z4aYZ/Z90mt/ez85lU4Q++Bstf3nuyf7jDBjKLu9s7WqxWaPWYd7+yj7dut3tT71iu8+DxJQf4v+5su2DSWiC0utLW+LlXU2nyUuF/c/wEK7+3lg==

RNG Seed: 1487660449

Unknown proc mask on {SpellID: 38308}
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:47 +0x10
panic({0xb6b40, 0x3b73320})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/Tereneckla/wotlk/sim/core.(*Unit).RegisterSpell(0x1cac000, {{0x95a4, 0x0, 0x0, 0x0}, 0x2, 0x0, 0x1800, 0x0, 0x0, ...})
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:190 +0xde
github.com/Tereneckla/wotlk/sim/core.(*Unit).GetOrRegisterSpell(0x1cac000, {{0x95a4, 0x0, 0x0, 0x0}, 0x2, 0x0, 0x1800, 0x0, 0x0, ...})
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:262 +0xd
github.com

**Comment by Tereneckla** [comment]
Fixed
