### ISSUE TITLE
Level 80 Spell Ranks

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#30]
**Describe the bug**
The sim is currently using level 80 spell ranks. This causes the sims to be inaccurate. Certain spells might be doing more damage than they normally would in a rotation causing result numbers, stat weights etc to be faulty.

**To Reproduce**
Sim with any class
Go to Results
Hover over a spell to see rank

**Expected behavior**
It should use the max rank of the spell available at level 70

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/65196200/222502413-52963b8c-73ab-48ea-a71a-dd96a3ceacb2.png)

Learn at level 77:
https://www.wowhead.com/wotlk/spell=47813/corruption

**Extra Notes**
I assume this would be a lot of work to fix but it is a pretty major issue

**Comment by Tereneckla** [comment]
That's just the UI, haven't gotten to that yet

**Comment by Tereneckla** [comment]
Fixed
