### ISSUE TITLE
Boss Armor Values

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#31]
**Describe the bug**
The armor values of the boss is by default set to 10643. This causes pets and physical dps to sim significantly lower than if the armor value was set lower.

**To Reproduce**
1. Pick a class to sim
2. Click on Settings tab
3. Click on Advanced under encounter settings
4. See armor value

**Expected behavior**
TBC bosses have 6200 or 7700 armor generally, so putting the default to one of those values, or the average of those would be nice.

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/65196200/222719900-eee463e5-d9bf-4a21-ad2d-92df9208d9ef.png)

**Source:**
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/137892-raid-raid-boss-armor.html
https://www.iqgaming.org/armorpentbc

**Comment by Tereneckla** [comment]
Is set to 6200 for a while already
Make a new target or clear your browser cache or cookies (actually no clue where this sim saves your settings)
