### ISSUE TITLE
Essence of the Martyr on-use effect

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#33]
**Describe the bug**
The aura from essence of the martyr on-use effect is currently giving 99 spell power. 

**To Reproduce**
1. Make a character on the sim
2. Equip essence of the martyr
3. Run simulation
4. Go to Log and find essence of the martyr aura

**Expected behavior**
The on-use effect from the trinket should give 158 spell power
https://www.wowhead.com/wotlk/item=29376/essence-of-the-martyr

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/65196200/222917282-6ba3325a-9a34-42be-a669-8e942a2233d1.png)

**Comment by Tereneckla** [comment]
Yeah, only copied their tbc sim implementation, didn't check if the trinkets had been changed
