### ISSUE TITLE
Icon of the Silver Crescent on-use effect

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#34]
**Describe the bug**
The aura from Icon of the Silver Crescent on-use effect is currently giving 155 spell power.

**To Reproduce**
1. Make a character on the sim
2. Equip Icon of the Silver Crescent
3. Run simulation
4. Go to Log and find Icon of the Silver Crescent aura

**Expected behavior**
The on-use effect from the trinket should give 158 spell power
https://www.wowhead.com/wotlk/item=29370/icon-of-the-silver-crescent

**Sim Link and Screenshots**
![image](https://user-images.githubusercontent.com/65196200/222917430-2935a9c3-45a8-4042-a4c4-734c991a6359.png)

**Additional Context**
I know 3 spell power is very small but since I reported the other trinket may as well also fix this since the trinkets are essentially identical

**Comment by Tereneckla** [comment]
Yeah, only copied their tbc sim implementation, didn't check if the trinkets had been changed
