### ISSUE TITLE
Essence of the Martyr and Icon of the Silver Crescent have no shared cooldown

### ISSUE THREAD

**Issue by Icebeam666** [Tereneckla/wotlk#35]
**Describe the bug**
Essence of the Martyr on-use effect and Icon of the Silver Crescent on-use effect are being used at the same time. So there is no cooldown after using the first trinket to when you can use the other tinket.

**To Reproduce**
1. Create a character to sim
2. Equip Essence of the Martyr and Icon of the Silver Crescent
3. Run simulation
4. Go to Log and see the time at which the trinkets are being used

**Expected behavior**
After you use one of the trinkets, the other one should be available to use 20 seconds after (thats how it works on chromie at least). Seeing as the on-use effect lasts 20 seconds, you can use the second trinket right as the first one falls off. But you should not be able to use both at the same time.

**Sim Links and Screenshots**
Notice the timestamps
![image](https://user-images.githubusercontent.com/65196200/222917889-9e8118df-956d-4ad1-994b-331dfe4a3ae1.png)
![image](https://user-images.githubusercontent.com/65196200/222917936-6aeb8123-a873-4534-955c-0ebd0ca0bfa1.png)

**Additional context**
I do not know if this applies to all trinkets on the website or just these two.

**Comment by Tereneckla** [comment]
Also caused by copy paste of tbc implementation
