### ISSUE TITLE
[Hunter] Sim uses level 80 hunter pets spells

### ISSUE THREAD

**Issue by hofik19** [Tereneckla/wotlk#40]
**Describe the bug**
When checking simulation results it shows lvl 80 abilities beeing used for pet

**To Reproduce**
1. Go to results after running a hunter sim
2. Hower over pet skill eg. "Bite"
3. See it showing level 80 version of abillity

**Expected behavior**
It should use max level 70 abilities

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/96583627/229082160-f863d607-a0f1-4b47-8042-dce0708a2c14.png)
[[https://tereneckla.github.io/wotlk/hunter/#eJy9U0FoE0EU3T+brJtNxbFZmjUITSNCEIXZxODGgzP2VA9qURC8taCCpYpUL/Zm6cmDR2lyEXIRD4KgQktoUdAYizElhVRtQdsakCJx20MrxYKzOyEoIhJY+5gHf/78//6bZUeTuqV2KTKpjIDSO9h/8+KQGsAocgdpITy3CUY+HFMW6pDZAnLV8mkqflkTUQhn3oPxlB+v12EhD+S6JWtBXKiBYSO3ogN/KoJR02MBfiwWGeJFGC/y/ERbTN5oZEK4UgVjVOej8rDR0ML4YxHcjNN4jWc6cKEOxovwr4LOoCB++xmMRb3hsLYG5AovV/HWKpABNxqZFxIqftX0X+D+V/TmBOH/+bKTJBdc2fv8MvMhctnyxdpULarEFRKyUB/kUAlpY0jaFhxj2zPHO7STVjuGpaM3NNoDcbTb3bN7rHuvhlQ/5w7OAKfKqXHKnGBmMw4maDrpYpb2QsRUZdwZCasIA5N75DFAjwCegVwEeAfQJUbZNF164+ArjcNt6EyZCUISxEyRlGkmEoeTJiGppJlMmYecYAl09W4Z4VwZRecqKD5dQaRaQV8AbPBnQfoAUhZJsWUUEPKnmLiBpLM9wuNrmhaZGdp1yUWVJh6j6AnDf+A//0P2LeaJjjXujU4LEN9s8hs7LvbfaR+c+e3VzZbGz/fbvqaznT8erFZOrlFv5tv0YCa4b3oQsSX/wxl2dpOWz00dOT280qK+7ZGff+PPV4dHc0+mdu1nf+v4CQH0uuM=](url)]

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version 111

**Additional context**
Whole pet calculations might be wrong and probably uses level 80 pet stats and skills. Pet DMG seems to be a lot higher than it should. I can provide proper values and skill links, just let me know what is needed.

**Comment by hofik19** [comment]
![image](https://user-images.githubusercontent.com/96583627/229084928-78d6d676-bf23-4dbf-aabd-eb5302e45410.png)
Another wrong spellit should use Rank 5 https://www.wowhead.com/wotlk/spell=64494/furious-howl

**Comment by Tereneckla** [comment]
It's visual, I only edited the values of the abilities

**Comment by hofik19** [comment]
Ok, I understand, but I still want to do some more tests for pet dmg calculation. Are those stats, visible in the log, are the pet stats before fight starts? I see them beeing changed dynamically when buffs kicks in
![image](https://user-images.githubusercontent.com/96583627/229090264-501ae6b2-0f0d-4879-ba4c-d2c717cf534e.png)

**Comment by hofik19** [comment]
There is a big difference in Bite DMG between server and sim. Test/sim was made without talents/buffs/debuffs. Only gear.
![image](https://user-images.githubusercontent.com/96583627/229101477-0b60dab6-969f-4d3f-aadc-6ef49fadb7c3.png)

**Comment by Tereneckla** [comment]
Oh yeah, missed the focus dump abilities in the sim
Only did all the other pet abilities

**Comment by Tereneckla** [comment]
Fixed the damage

**Comment by hofik19** [comment]
How about the Pet stats in log? Cos if the stats in log are showing used values than there could be another issue with them beeing too high.
Character stats are correct on both server and sim, but pet have much more Strength and AP, (Agi is also weird but not by much)
![image](https://user-images.githubusercontent.com/96583627/229113927-8cbdc573-e8e7-4320-b593-0e6d67bd3bd6.png)
No talents/buffs/debuffs, only bow cos it won't sim without a weapon.

**Comment by Tereneckla** [comment]
Done as well

**Comment by hofik19** [comment]
Thank you! Now it looks more accurate:
Pre-Raid BiS before fixes:
![image](https://user-images.githubusercontent.com/96583627/229172417-a329da9e-ad12-4f76-975a-ffc7543a5060.png)
and after:
![image](https://user-images.githubusercontent.com/96583627/229172464-7c30b519-2ff5-4769-b18f-da21a8efc6f0.png)
