### ISSUE TITLE
[Hunter] Sim uses Aspect of the Dragonhawk instead of Aspect of the Hawk

### ISSUE THREAD

**Issue by hofik19** [Tereneckla/wotlk#41]
**Describe the bug**
As in title, sim shows AotD on "Buffs" tab in results section.

**To Reproduce**
1. Go to "results" -> "buffs"after running a hunter sim
2. See Aspect of the Dragonhawk on top

**Expected behavior**
It should use Aspect of the Hawk https://www.wowhead.com/wotlk/spell=27044/aspect-of-the-hawk

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/96583627/229084545-41f786b7-d373-4cbd-a4ff-edc4bf828674.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version 111

**Comment by Tereneckla** [comment]
It's visual, I only edited the attack power values of the aspect
