### ISSUE TITLE
Crit: Base -1.49% Hunter Sim. 

### ISSUE THREAD

**Issue by BugSquisher9000** [Tereneckla/wotlk#42]
**Describe the bug**
![image](https://github.com/Tereneckla/wotlk/assets/131832227/3c208e5b-4bbf-4d75-a621-4dd31844a03c)

**To Reproduce**
I dont know how it happen

**Expected behavior**
Should not give me -1.49 crit

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://tereneckla.github.io/wotlk/hunter/#eJzjkuJgEmAyYLJgDGBKYCxg6mBk2sDIdIGR8QUjoxMvB6MCkwajA2MF4wpGRiEGqQssTYxsATmJlalFHIwCTFJKXAyEoBIXB5cCmwG/BVMAxyKms0xcM5gYRgFWIGRAqo4qDlA0SDAVMFrlcDl6MGowCYLFHeY7OClwMXGwAjE7EHMCMQcQcwExMxAzATGj4ayZILDT3tIYDC7bS6lzMAvIS/ECkwQjMNqZPZgPMDIrQqz6YG959gwIvLHXYOxiVNQ1MDTVNTUAAmMjEAUywcDU2MjQ2NTYwNDY0PARowjHgvNMAoufMilcv8SkceoSk8G1S0wvGFk+MLLPYmS4xcgwi4lB6TETJ9j8hjQHiNsZRBwkIS47aW8JEblgr5gGBtfsjTYzKXhKsGrROBV9aHSgijkWO6hjDgkAEmZ73zs4Qvg/7BMYg1DyHSS6WaEue2APCe2P9lRygAPMXluu64sLbL/Zy7e+Dtwh95VE8z9Qyz0EAWa+83hYJbLOXdIBlw4A1gxlvQ==)

![image](https://github.com/Tereneckla/wotlk/assets/131832227/ef03cd39-016d-42f0-bea4-e447bd1db7fd)

**Desktop (please complete the following information):**
 - OS: Win11
 - Chrome and Edge

**Comment by Tereneckla** [comment]
Sorry, typo while increasing the accuracy of the agility crit scaling
base crit of hunter is -1.53% btw
