### ISSUE TITLE
[Engineering] Super Sapper Charge error

### ISSUE THREAD

**Issue by Hogofogo1** [Tereneckla/wotlk#43]
**Describe the bug**
When checking Super Sapper Charge as Engineer and running Simulation I get en error.

**To Reproduce**
1. Create any character
2. Pick Engineering profession
3. Check Super Sapper Charge
4. Run Simulation

**Expected behavior**
no errors would be lovely

**Sim Links and Screenshots**
![Screenshot 2023-08-09 091404](https://github.com/Tereneckla/wotlk/assets/97225391/4685f6b9-3d61-4cf6-bf87-a18592beec0a)

**Desktop (please complete the following information):**
 - OS: win11
 - Browser: Edge
 - Version: latest

**Additional context**

**Comment by Tereneckla** [comment]
Can you share your full setup please?
Export -> Link

**Comment by Hogofogo1** [comment]
Here:
https://tereneckla.github.io/wotlk/warrior/#eJzjkuFgMmAMYIxgrGDsYGScwMi4gpHxAiPjC0bGH4yMTvwKQLkCqDBQTIhBqpWtiZEtICexMrWIg1WAU6qBiUtY4PovRond4kpsv3YzrulmMsizYOHiEDj6lBHMEhaY8oFRYhVQ+vptxhu3GQ0qgIICAof3Mkp8YFJi/vGO0SATKCImcPsRo8RTESVOoCkQBFYpLPD7AaPEdREltkvvwIK1QEFugQfbGSXWsBoUWzADzXr9gFGJ7c8Pxm9QaTGByUArj4hjmnXtBKPEHzGwS0GCBUDtHAI/H0OcwCGw4SejQQqYdRzqeg6BptsQddwCk+8xSrwWMagGCjOAlLxhNMi3YFLi4uBSYNVgjeCpYFzEdJaJawYTwyjACoQMSNVRxcbBKMGowFjkxGUjAEqICkyOYImGMAdPCCPQIRCiNtIhEsLQc8gApucZjIwLGSECJg5STBqMXYzKxgZGRgbGRoZGxsbGpoYGYGBoZGRobGRsaGRqqGtsYPqIUYRj/mUmgRmXmRRaLjNpNF9mMmi9zPSCkekDI8ssRoZbjAyzmBiULjJxQqxPcxCEWCLiIDlrJgictDfazKTgKcGqReOU8KHRgSrmWOygjjkkAEswufe9AyQ2GX7YJzAGgfNOGhgwwVxEZZd9sIeZC7Nn30Wtb/yxn+zXrXqSlL38o/3zS7u3+QU8tsdlwrLI+hL27XNwytMKCBmslJTV/Vyq4UCsDgCC7q7i

**Comment by Tereneckla** [comment]
The sapper self damage tried to apply deep wounds
Fixed now

**Comment by Hogofogo1** [comment]
awesome, thx
